version: '3'
services:
  db:
    container_name: mongodb
    image: "mongodb/mongodb-community-server:6.0-ubi8"
    volumes:
      - db-data:/data

  web:
    container_name: saunaServer
    build: ./saunaServer/
    ports:
      #host:container
      - "8080:8080"
    environment:
      PORT: 8080
      MONGODB_URI: "mongodb://mongodb:27017/saunaTemps"
    depends_on:
      - db
  
  #new stuff also changed build dir
  front:
      container_name: saunaFront
      build: ./saunaFront/
      ports:
        - "3000:3000"

volumes:
  db-data: {}